export const mockBookedDrones = [
  {
    serviceId: "1111",
    farmlandName: "WestPlot A",
    landType: "Crop",
    service: "Rental: Data Collection",
    startTime: "",
    endTime: "06/29/2022",
    status: "active",
  },
  {
    serviceId: "1113",
    farmlandName: "North Plot A",
    landType: "Crop",
    service: "Rental: Data Collection",
    startTime: "07/01/2022",
    endTime: "06/29/2022",
    status: "booked",
  },
  {
    serviceId: "1300",
    farmlandName: "WestPlot",
    landType: "Crop",
    service: "Rental: Data Collection",
    startTime: "07/01/2022",
    endTime: "06/29/2022",
    status: "booked",
  },
  {
    serviceId: "1222",
    farmlandName: "WestPlot",
    landType: "Crop",
    service: "Rental: Data Collection",
    startTime: "06/09/2023",
    endTime: "06/29/2023",
    status: "active",
  },
  {
    serviceId: "1100",
    farmlandName: "WestPlot",
    landType: "Crop",
    service: "Rental: Data Collection",
    startTime: "",
    endTime: "06/29/2022",
    status: "active",
  },
  {
    serviceId: "1112",
    farmlandName: "WestPlot",
    landType: "Crop",
    service: "Rental: Data Collection",
    startTime: "",
    endTime: "06/29/2022",
    status: "finished",
  },
  {
    serviceId: "1112",
    farmlandName: "WestPlot",
    landType: "Crop",
    service: "Rental: Data Collection",
    startTime: "",
    endTime: "06/29/2022",
    status: "finished",
  },
  {
    serviceId: "1112",
    farmlandName: "WestPlot",
    landType: "Crop",
    service: "Rental: Data Collection",
    startTime: "",
    endTime: "06/29/2022",
    status: "finished",
  },
];
