export const mockDrones = [
  {
    drone_id: 14550,
    drone_maker: "DJI",
    drone_model: "DJI",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14551,
    drone_maker: "DJI",
    drone_model: "Mini SE",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14552,
    drone_maker: "DJI",
    drone_model: "Mini SE",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14553,
    drone_maker: "DJI",
    drone_model: "Mini SE",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14554,
    drone_maker: "DJI",
    drone_model: "Mini SE",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14555,
    drone_maker: "DJI",
    drone_model: "Mini SE",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14556,
    drone_maker: "DJI",
    drone_model: "Mini SE",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14557,
    drone_maker: "DJI",
    drone_model: "Mini SE",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14558,
    drone_maker: "DJI",
    drone_model: "Mini SE",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14559,
    drone_maker: "DJI",
    drone_model: "Mini SE",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14560,
    drone_maker: "DJI",
    drone_model: "Phantom 4 Pro",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14561,
    drone_maker: "DJI",
    drone_model: "Phantom 4 Pro",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14562,
    drone_maker: "DJI",
    drone_model: "Phantom 4 Pro",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14563,
    drone_maker: "DJI",
    drone_model: "Phantom 4 Pro",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14564,
    drone_maker: "DJI",
    drone_model: "Phantom 4 Pro",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14565,
    drone_maker: "DJI",
    drone_model: "Phantom 4 Pro",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14566,
    drone_maker: "DJI",
    drone_model: "Phantom 4 Pro",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14567,
    drone_maker: "DJI",
    drone_model: "Phantom 4 Pro",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14568,
    drone_maker: "DJI",
    drone_model: "Phantom 4 Pro",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14569,
    drone_maker: "DJI",
    drone_model: "Phantom 4 Pro",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14570,
    drone_maker: "DJI",
    drone_model: "Matrice 300 RTK",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "payload",
    status: "registered",
  },
  {
    drone_id: 14571,
    drone_maker: "DJI",
    drone_model: "Matrice 300 RTK",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "payload",
    status: "registered",
  },
  {
    drone_id: 14572,
    drone_maker: "DJI",
    drone_model: "Matrice 300 RTK",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "payload",
    status: "registered",
  },
  {
    drone_id: 14573,
    drone_maker: "DJI",
    drone_model: "Matrice 300 RTK",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "payload",
    status: "registered",
  },
  {
    drone_id: 14574,
    drone_maker: "DJI",
    drone_model: "Matrice 300 RTK",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "payload",
    status: "registered",
  },
  {
    drone_id: 14575,
    drone_maker: "DJI",
    drone_model: "Matrice 300 RTK",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "payload",
    status: "registered",
  },
  {
    drone_id: 14576,
    drone_maker: "DJI",
    drone_model: "Matrice 300 RTK",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "payload",
    status: "registered",
  },
  {
    drone_id: 14577,
    drone_maker: "DJI",
    drone_model: "Matrice 300 RTK",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "payload",
    status: "registered",
  },
  {
    drone_id: 14578,
    drone_maker: "DJI",
    drone_model: "Matrice 300 RTK",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "payload",
    status: "registered",
  },
  {
    drone_id: 14579,
    drone_maker: "DJI",
    drone_model: "Matrice 300 RTK",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "payload",
    status: "registered",
  },
  {
    drone_id: 14580,
    drone_maker: "DJI",
    drone_model: "Agras T20",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "payload",
    status: "registered",
  },
  {
    drone_id: 14581,
    drone_maker: "DJI",
    drone_model: "Agras T20",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "payload",
    status: "registered",
  },
  {
    drone_id: 14582,
    drone_maker: "DJI",
    drone_model: "Agras T20",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "payload",
    status: "registered",
  },
  {
    drone_id: 14583,
    drone_maker: "DJI",
    drone_model: "Agras T20",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "payload",
    status: "registered",
  },
  {
    drone_id: 14584,
    drone_maker: "DJI",
    drone_model: "Agras T20",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "payload",
    status: "registered",
  },
  {
    drone_id: 14585,
    drone_maker: "DJI",
    drone_model: "Agras T20",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "payload",
    status: "registered",
  },
  {
    drone_id: 14586,
    drone_maker: "DJI",
    drone_model: "Agras T20",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "payload",
    status: "registered",
  },
  {
    drone_id: 14587,
    drone_maker: "DJI",
    drone_model: "Agras T20",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "payload",
    status: "registered",
  },
  {
    drone_id: 14588,
    drone_maker: "DJI",
    drone_model: "Agras T20",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "payload",
    status: "registered",
  },
  {
    drone_id: 14589,
    drone_maker: "DJI",
    drone_model: "Agras T20",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "payload",
    status: "registered",
  },
  {
    drone_id: 14590,
    drone_maker: "Parrot",
    drone_model: "Anafi Thermal",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14591,
    drone_maker: "Parrot",
    drone_model: "Anafi Thermal",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14592,
    drone_maker: "Parrot",
    drone_model: "Anafi Thermal",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14593,
    drone_maker: "Parrot",
    drone_model: "Anafi Thermal",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14594,
    drone_maker: "Parrot",
    drone_model: "Anafi Thermal",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14595,
    drone_maker: "Parrot",
    drone_model: "Anafi Thermal",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14596,
    drone_maker: "Parrot",
    drone_model: "Anafi Thermal",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14597,
    drone_maker: "Parrot",
    drone_model: "Anafi Thermal",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14598,
    drone_maker: "Parrot",
    drone_model: "Anafi Thermal",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14599,
    drone_maker: "Parrot",
    drone_model: "Anafi Thermal",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14600,
    drone_maker: "Lumenier",
    drone_model: "QAV250",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14601,
    drone_maker: "Lumenier",
    drone_model: "QAV250",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14602,
    drone_maker: "Lumenier",
    drone_model: "QAV250",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14603,
    drone_maker: "Lumenier",
    drone_model: "QAV250",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14604,
    drone_maker: "Lumenier",
    drone_model: "QAV250",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14605,
    drone_maker: "Lumenier",
    drone_model: "QAV250",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14606,
    drone_maker: "Lumenier",
    drone_model: "QAV250",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14607,
    drone_maker: "Lumenier",
    drone_model: "QAV250",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14608,
    drone_maker: "Lumenier",
    drone_model: "QAV250",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14609,
    drone_maker: "Lumenier",
    drone_model: "QAV250",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14610,
    drone_maker: "Holybro",
    drone_model: "X500 V2",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14611,
    drone_maker: "Holybro",
    drone_model: "X500 V2",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14612,
    drone_maker: "Holybro",
    drone_model: "X500 V2",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14613,
    drone_maker: "Holybro",
    drone_model: "X500 V2",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14614,
    drone_maker: "Holybro",
    drone_model: "X500 V2",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14615,
    drone_maker: "Holybro",
    drone_model: "X500 V2",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14616,
    drone_maker: "Holybro",
    drone_model: "X500 V2",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14617,
    drone_maker: "Holybro",
    drone_model: "X500 V2",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14618,
    drone_maker: "Holybro",
    drone_model: "X500 V2",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14619,
    drone_maker: "Holybro",
    drone_model: "X500 V2",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14620,
    drone_maker: "Yuneec",
    drone_model: "H850 RTK",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14621,
    drone_maker: "Yuneec",
    drone_model: "H850 RTK",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14622,
    drone_maker: "Yuneec",
    drone_model: "H850 RTK",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14623,
    drone_maker: "Yuneec",
    drone_model: "H850 RTK",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14624,
    drone_maker: "Yuneec",
    drone_model: "H850 RTK",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14625,
    drone_maker: "Yuneec",
    drone_model: "H850 RTK",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14626,
    drone_maker: "Yuneec",
    drone_model: "H850 RTK",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14627,
    drone_maker: "Yuneec",
    drone_model: "H850 RTK",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14628,
    drone_maker: "Yuneec",
    drone_model: "H850 RTK",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14629,
    drone_maker: "Yuneec",
    drone_model: "H850 RTK",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 14630,
    drone_maker: "Autel Robotics",
    drone_model: "EVO II 640T",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14631,
    drone_maker: "Autel Robotics",
    drone_model: "EVO II 640T",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14632,
    drone_maker: "Autel Robotics",
    drone_model: "EVO II 640T",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14633,
    drone_maker: "Autel Robotics",
    drone_model: "EVO II 640T",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14634,
    drone_maker: "Autel Robotics",
    drone_model: "EVO II 640T",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14635,
    drone_maker: "Autel Robotics",
    drone_model: "EVO II 640T",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14636,
    drone_maker: "Autel Robotics",
    drone_model: "EVO II 640T",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14637,
    drone_maker: "Autel Robotics",
    drone_model: "EVO II 640T",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14638,
    drone_maker: "Autel Robotics",
    drone_model: "EVO II 640T",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 14639,
    drone_maker: "Autel Robotics",
    drone_model: "EVO II 640T",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "surveillance",
    status: "registered",
  },
  {
    drone_id: 44442,
    drone_maker: "Parrot",
    drone_model: "PF728000 ANAFI",
    drone_type: "drone",
    farmer_id: null,
    land_id: null,
    mission_id: null,
    pilot_id: null,
    service_type: "data collection",
    status: "registered",
  },
  {
    drone_id: 62230,
    drone_maker: "Parrot",
    drone_model: "Parrot Ultra Mini",
    drone_type: "drone",
    farmer_id: 1,
    land_id: 1,
    mission_id: 1,
    pilot_id: 1,
    service_type: "surveillance",
    status: "connected",
  },
];
